In [1]:
import tensorflow as tf
print(tf.__version__)

2.3.1


In [2]:
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences

In [8]:
# Example text
sentences = [
    "I am the best man.",
    "I love to go to the gym.",
    "I hate onions."
]

In [9]:
MAX_VOCAB_SIZE = 20000
tokenizer = Tokenizer(num_words=MAX_VOCAB_SIZE)
tokenizer.fit_on_texts(sentences)
sequences = tokenizer.texts_to_sequences(sentences)

In [10]:
print(sequences)

[[1, 4, 2, 5, 6], [1, 7, 3, 8, 3, 2, 9], [1, 10, 11]]


In [11]:
# Geting the word to index mapping
tokenizer.word_index

{'i': 1,
 'the': 2,
 'to': 3,
 'am': 4,
 'best': 5,
 'man': 6,
 'love': 7,
 'go': 8,
 'gym': 9,
 'hate': 10,
 'onions': 11}

In [ ]:
# Padding
# Arguements (maxlen,padding,trucating)

In [12]:
# use the defaults
data = pad_sequences(sequences)
print(data)

[[ 0  0  1  4  2  5  6]
 [ 1  7  3  8  3  2  9]
 [ 0  0  0  0  1 10 11]]


In [13]:
MAX_SEQUENCE_LENGTH = 5
data = pad_sequences(sequences, maxlen=MAX_SEQUENCE_LENGTH)
print(data)

[[ 1  4  2  5  6]
 [ 3  8  3  2  9]
 [ 0  0  1 10 11]]


In [14]:
data = pad_sequences(sequences, maxlen=MAX_SEQUENCE_LENGTH, padding='post')
print(data)

[[ 1  4  2  5  6]
 [ 3  8  3  2  9]
 [ 1 10 11  0  0]]


In [15]:
# too much padding
data = pad_sequences(sequences, maxlen=6)
print(data)

[[ 0  1  4  2  5  6]
 [ 7  3  8  3  2  9]
 [ 0  0  0  1 10 11]]


In [16]:
# truncation
data = pad_sequences(sequences, maxlen=4)
print(data)

[[ 4  2  5  6]
 [ 8  3  2  9]
 [ 0  1 10 11]]


In [17]:
data = pad_sequences(sequences, maxlen=4, truncating='post')
print(data)

[[ 1  4  2  5]
 [ 1  7  3  8]
 [ 0  1 10 11]]
